<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Адрес' => 'Мекен-жай',
    'Врачи-специалисты' => 'Медицина мамандары',
    'Всегда открыт' => 'Әрқашан ашық',
    'Главная' => 'Басты бет',
    'Записаться' => 'Жазылу',
    'Контакты' => 'Байланыс',
    'Лабораторный тест' => 'Зертханалық сынақ',
    'Лекарственное обеспечение' => 'ДӘРІ-ДӘРМЕКПЕН ҚАМТАМАССЫЗ ЕТУ',
    'Лицензия' => 'Лицензия',
    'Личная забота для вашего здорового образа жизни' => 'Сіздің салауатты өмір салтыңызға жеке күтім',
    'Мы делаем жизнь наших пациентов лучше' => 'Біз пациенттеріміздің өмірін жақсартамыз',
    'НАПИШИТЕ НАМ' => 'Бізге жазыңыз',
    'Населению' => 'ХАЛЫҚҚА',
    'Новости' => 'Жаңалықтар',
    'Новости & Блог' => 'Жаңалықтар & Блог',
    'Номера телефона' => 'Телефон нөмері',
    'О деятельности' => 'ҚЫЗМЕТІ ТУРАЛЫ',
    'О нашем центре' => 'Біз туралы',
    'О центре' => 'Орталық туралы',
    'Отправить' => 'Жіберу',
    'Посетите нашу клинику круглосуточно' => 'Біздің клиника тәулік бойы істейді',
    'Последние новости нашей поликлиники' => 'Біздің клиникадағы соңғы жаңалықтар',
    'Связаться' => 'Байланысу',
    'Связаться с нами' => 'Байланысу',
    'Скорая помощь' => 'Жедел жәрдем',
    'Скрининг населения' => 'ХАЛЫҚТЫҢ СКРИНИНГ',
    'Специалисты' => 'МАМАНДАР',
    'Структура' => 'ҚҰРЫЛЫМЫ',
    'Услуги' => 'ҚЫЗМЕТІ ТУРАЛЫ',
    'Цели и задачи' => 'МАҚСАТЫ',
];
