<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Адрес' => '',
    'Врачи-специалисты' => '',
    'Всегда открыт' => '',
    'Главная' => '',
    'Записаться' => '',
    'Контакты' => '',
    'Лабораторный тест' => '',
    'Лекарственное обеспечение' => '',
    'Лицензия' => '',
    'Личная забота для вашего здорового образа жизни' => '',
    'Мы делаем жизнь наших пациентов лучше' => '',
    'НАПИШИТЕ НАМ' => '',
    'Населению' => '',
    'Новости' => '',
    'Новости & Блог' => '',
    'Номера телефона' => '',
    'О деятельности' => '',
    'О нашем центре' => '',
    'О центре' => '',
    'Отправить' => '',
    'Посетите нашу клинику круглосуточно' => '',
    'Последние новости нашей поликлиники' => '',
    'Связаться' => '',
    'Связаться с нами' => '',
    'Скорая помощь' => '',
    'Скрининг населения' => '',
    'Специалисты' => '',
    'Структура' => '',
    'Услуги' => '',
    'Цели и задачи' => '',
];
